### ISSUE TITLE
Embedding Method

### ISSUE THREAD

**Issue by ghost** [KDD-HIEPT/DeepLink#1]
What kind of embedding method do you use?
May I refer to your code of network embedding? Thank you very much.

**Comment by KDD-HIEPT** [comment]
I add the `embedding.py` file in `src` folder，you canrefer it.

**Comment by KDD-HIEPT** [comment]
> What kind of embedding method do you use?
> May I refer to your code of network embedding? Thank you very much.

I add the `embedding.py` file in `src ` folder，you can refer it.
