### ISSUE TITLE
embedding file

### ISSUE THREAD

**Issue by ImmortalFish** [KDD-HIEPT/DeepLink#2]
Hello, I run the `embedding.py` in `src`, but using `emb` and `vocab` generated by `embedding.py` to run `main.py` doesn't work very well.  Is there a problem with the parameters in the  `embedding.py`? (I only change `size`  to 800, and I'm using the same dataset as in your paper)

**Comment by KDD-HIEPT** [comment]
try a bigger parameter `’num_path ` will get a better result, however, it will take more time.
